export const clerkAuthAppearance = {
  variables: {
    colorPrimary: "#2563eb",
    colorBackground: "#ffffff",
    colorInputBackground: "#fafafa",
    colorText: "#18181b",
    colorTextSecondary: "#52525b",
    borderRadius: "0.625rem",
  },
  elements: {
    rootBox: "mx-auto w-full max-w-md",
    card: "bg-white border border-[#d4d4d8] shadow-sm rounded-xl font-body",
    headerTitle: "font-body text-lg font-semibold text-[#18181b]",
    headerSubtitle: "font-body text-sm text-[#52525b]",
    formButtonPrimary: "bg-[#2563eb] hover:bg-[#1d4ed8] text-white font-semibold rounded-lg",
    formFieldInput: "bg-[#fafafa] border border-[#d4d4d8] text-[#18181b] font-body rounded-lg text-base",
    formFieldLabel: "font-body text-sm font-medium text-[#18181b]",
    formFieldErrorText: "font-body text-sm text-retro-error font-medium",
    alertText: "font-body text-sm text-retro-error",
    footerActionLink: "text-[#2563eb] font-semibold underline",
    identityPreviewText: "font-body text-sm text-[#18181b]",
    formFieldSuccessText: "font-body text-sm text-[#22C55E]",
    captcha: "my-4 flex justify-center",
    captchaWidget: "mx-auto",
  },
} as const;
