export const clerkAuthAppearance = {
  variables: {
    colorPrimary: "#43e660",
    colorBackground: "#ffffff",
    colorInputBackground: "#f7f7f5",
    colorText: "#1a1a1a",
    colorTextSecondary: "#676767",
    borderRadius: "0.75rem",
  },
  elements: {
    rootBox: "mx-auto w-full max-w-md",
    card: "bg-white border border-[#e8e8e8] shadow-sm rounded-xl font-body",
    headerTitle: "font-body text-lg font-semibold text-[#1a1a1a]",
    headerSubtitle: "font-body text-sm text-[#676767]",
    formButtonPrimary: "bg-[#43e660] hover:bg-[#3dd656] text-[#1a1a1a] font-semibold rounded-lg",
    formFieldInput: "bg-[#f7f7f5] border border-[#e8e8e8] text-[#1a1a1a] font-body rounded-lg",
    formFieldLabel: "font-body text-sm font-medium text-[#1a1a1a]",
    formFieldErrorText: "font-body text-sm text-retro-error font-medium",
    alertText: "font-body text-sm text-retro-error",
    footerActionLink: "text-[#1a1a1a] font-semibold underline",
    identityPreviewText: "font-body text-sm text-[#1a1a1a]",
    formFieldSuccessText: "font-body text-sm text-[#22C55E]",
    captcha: "my-4 flex justify-center",
    captchaWidget: "mx-auto",
  },
} as const;
